name: 🐛 Bug Report
description: File a bug report to help us improve
title: "[Bug]: "
labels: ["bug", "triage"]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report! Please provide as much detail as possible.

  - type: checkboxes
    id: terms
    attributes:
      label: Prerequisites
      description: Please confirm the following before submitting your bug report
      options:
        - label: I have searched for existing issues that describe my problem
          required: false
        - label: I have read the [documentation](https://github.com/Nuralyio/the-agent/blob/main/README.md)
          required: false
        - label: I am using the latest version of The Agent
          required: false

  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: A clear and concise description of what the bug is
      placeholder: Tell us what you see!
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
      description: What did you expect to happen?
      placeholder: Tell us what you expected to see!
    validations:
      required: false

  - type: textarea
    id: steps
    attributes:
      label: Steps to reproduce
      description: Please provide step-by-step instructions to reproduce the issue
      placeholder: |
        1. Go to '...'
        2. Click on '....'
        3. Scroll down to '....'
        4. See error
    validations:
      required: false

  - type: dropdown
    id: browser-adapter
    attributes:
      label: Browser Adapter
      description: Which browser adapter were you using?
      options:
        - Playwright (recommended)
        - Puppeteer
        - Selenium
        - Not applicable
    validations:
      required: false

  - type: dropdown
    id: ai-provider
    attributes:
      label: AI Provider
      description: Which AI provider were you using?
      options:
        - Ollama
        - OpenAI
        - Mistral
        - Not applicable
    validations:
      required: false

  - type: input
    id: version
    attributes:
      label: Version
      description: What version of The Agent are you running?
      placeholder: "v0.1.0-alpha"
    validations:
      required: false

  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: Please provide your environment details
      value: |
        - OS: [e.g. macOS 14.0, Windows 11, Ubuntu 22.04]
        - Node.js version: [e.g. 18.17.0]
        - npm version: [e.g. 9.6.7]
        - Browser version: [e.g. Chrome 120.0.6099.109]
    validations:
      required: false

  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
      render: shell

  - type: textarea
    id: additional-context
    attributes:
      label: Additional context
      description: Add any other context about the problem here, such as screenshots, configuration files, etc.
