name: 💡 Feature Request
description: Suggest an idea for this project
title: "[Feature]: "
labels: ["enhancement", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a new feature! Please provide as much detail as possible.

  - type: checkboxes
    id: terms
    attributes:
      label: Prerequisites
      description: Please confirm the following before submitting your feature request
      options:
        - label: I have searched for existing issues that describe this feature
          required: true
        - label: I have read the [documentation](https://github.com/Nuralyio/the-agent/blob/main/README.md)
          required: true
        - label: This feature would be useful to other users, not just me
          required: true

  - type: textarea
    id: problem
    attributes:
      label: Is your feature request related to a problem?
      description: A clear and concise description of what the problem is
      placeholder: "I'm always frustrated when..."
    validations:
      required: false

  - type: textarea
    id: solution
    attributes:
      label: Describe the solution you'd like
      description: A clear and concise description of what you want to happen
      placeholder: "I would like to see..."
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Describe alternatives you've considered
      description: A clear and concise description of any alternative solutions or features you've considered
      placeholder: "I've also considered..."
    validations:
      required: false

  - type: dropdown
    id: component
    attributes:
      label: Which component does this feature affect?
      description: Select the primary component this feature would impact
      options:
        - Core automation framework
        - API server
        - Web UI dashboard
        - CLI interface
        - MCP server
        - Documentation
        - Testing infrastructure
        - CI/CD workflows
        - Multiple components
        - Other
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this feature to you?
      options:
        - Low - Nice to have
        - Medium - Would improve my workflow
        - High - Blocking my use case
    validations:
      required: true

  - type: textarea
    id: use-case
    attributes:
      label: Use case
      description: Describe your specific use case for this feature
      placeholder: "I want to use this feature to..."
    validations:
      required: true

  - type: textarea
    id: additional-context
    attributes:
      label: Additional context
      description: Add any other context, screenshots, mockups, or examples about the feature request here
