name: CI Tests

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]

jobs:
  test:
    runs-on: ubuntu-latest
    environment: ci # This references the environment you configured

    strategy:
      matrix:
        node-version: [20.x]
        browser: [chrome]
        adapter: [playwright]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: |
          if [ -f package-lock.json ]; then
            npm ci
          else
            npm install
          fi

      - name: Install Playwright browsers
        run: npm run install:browsers

      - name: Run ESLint
        run: npm run lint

      - name: Run TypeScript check
        run: npm run typecheck

      - name: Build all packages
        run: npm run build

      - name: Run unit tests
        run: npm run test:unit
        env:
          CI: true

      - name: Run integration tests
        run: npm run test:integration
        env:
          CI: true
          BROWSER_HEADLESS: true
          BROWSER_TYPE: ${{ matrix.browser }}
          BROWSER_ADAPTER: ${{ matrix.adapter }}
          # AI Provider Configuration
          DEFAULT_AI_PROVIDER: ${{ vars.DEFAULT_AI_PROVIDER }}
          OLLAMA_BASE_URL: ${{ vars.OLLAMA_BASE_URL }}
          OLLAMA_MODEL: ${{ vars.OLLAMA_MODEL }}
          OLLAMA_TEMPERATURE: ${{ vars.OLLAMA_TEMPERATURE }}

      - name: Upload integration test artifacts
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: integration-test-artifacts-${{ matrix.browser }}-${{ matrix.adapter }}
          path: |
            packages/core/execution-logs/
            packages/core/screenshots/
          retention-days: 7
