export const styles = {
  container: {
    display: 'flex',
    height: '100vh',
    backgroundColor: '#212121',
    color: '#ffffff',
    fontFamily: '-apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, "Helvetica Neue", Arial, sans-serif',
  },
  leftSidebar: {
    width: '320px',
    backgroundColor: '#171717',
    borderRight: '1px solid #2a2a2a',
    display: 'flex',
    flexDirection: 'column' as const,
    overflow: 'hidden',
  },
  rightPanel: {
    flex: 1,
    backgroundColor: '#212121',
    display: 'flex',
    flexDirection: 'row' as const,
  },
  sidebarHeader: {
    padding: '16px 20px',
    borderBottom: '1px solid #2a2a2a',
    backgroundColor: '#171717',
  },
  title: {
    fontSize: '18px',
    fontWeight: '600',
    marginBottom: '4px',
    color: '#ffffff',
  },
  subtitle: {
    fontSize: '13px',
    color: '#9ca3af',
    fontWeight: '400',
  },
  sectionTitle: {
    fontSize: '14px',
    fontWeight: '600',
    marginBottom: '8px',
    color: '#e5e7eb',
  },
  tabNavigation: {
    display: 'flex',
    padding: '8px 12px',
    backgroundColor: '#1a1a1a',
    borderBottom: '1px solid #2a2a2a',
  },
  tabButton: {
    flex: 1,
    padding: '8px 16px',
    backgroundColor: 'transparent',
    border: 'none',
    color: '#9ca3af',
    fontSize: '13px',
    fontWeight: '500',
    cursor: 'pointer',
    borderRadius: '6px',
    transition: 'all 0.15s ease',
    margin: '0 2px',
  },
  tabButtonActive: {
    backgroundColor: '#374151',
    color: '#ffffff',
  },
  chatContainer: {
    flex: 1,
    display: 'flex',
    flexDirection: 'column' as const,
    gap: '12px',
    padding: '16px',
    overflowY: 'auto' as const,
    scrollbarWidth: 'thin' as const,
  },
  messageGroup: {
    display: 'flex',
    flexDirection: 'column' as const,
    gap: '8px',
  },
  messageWrapper: {
    display: 'flex',
    alignItems: 'flex-start',
    gap: '12px',
    maxWidth: '100%',
  },
  messageWrapperUser: {
    flexDirection: 'row-reverse' as const,
  },
  avatar: {
    width: '28px',
    height: '28px',
    borderRadius: '50%',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    fontSize: '14px',
    flexShrink: 0,
  },
  avatarSystem: {
    backgroundColor: '#10a37f',
    color: '#ffffff',
  },
  avatarUser: {
    backgroundColor: '#007ACC',
    color: '#ffffff',
  },
  messageBubble: {
    backgroundColor: '#2a2a2a',
    borderRadius: '12px',
    padding: '12px 16px',
    maxWidth: '85%',
    position: 'relative' as const,
  },
  messageBubbleUser: {
    backgroundColor: '#007ACC',
    marginLeft: 'auto',
  },
  messageText: {
    fontSize: '14px',
    lineHeight: '1.5',
    color: '#ffffff',
    margin: 0,
  },
  messageTime: {
    fontSize: '11px',
    color: '#6b7280',
    marginTop: '6px',
    textAlign: 'right' as const,
  },
  stepBubble: {
    backgroundColor: '#1f2937',
    border: '1px solid #007ACC',
    borderRadius: '8px',
    padding: '10px 14px',
    margin: '4px 0',
    maxWidth: '90%',
    alignSelf: 'flex-end' as const,
  },
  stepHeader: {
    display: 'flex',
    alignItems: 'center',
    gap: '8px',
    marginBottom: '4px',
  },
  stepTitle: {
    fontSize: '13px',
    fontWeight: '500',
    color: '#007ACC',
  },
  stepDescription: {
    fontSize: '12px',
    color: '#9ca3af',
    lineHeight: '1.3',
  },
  planBubble: {
    backgroundColor: '#1f2937',
    border: '1px solid #10b981',
    borderRadius: '8px',
    padding: '14px',
    margin: '4px 0',
    maxWidth: '95%',
    alignSelf: 'flex-end' as const,
  },
  planHeader: {
    display: 'flex',
    alignItems: 'center',
    gap: '8px',
    marginBottom: '12px',
  },
  planTitle: {
    fontSize: '14px',
    fontWeight: '600',
    color: '#10b981',
  },
  planSteps: {
    display: 'flex',
    flexDirection: 'column' as const,
    gap: '8px',
  },
  planStep: {
    display: 'flex',
    alignItems: 'center',
    gap: '10px',
    padding: '8px 12px',
    backgroundColor: '#374151',
    borderRadius: '6px',
    transition: 'all 0.2s ease',
    cursor: 'pointer',
  },
  planStepRunning: {
    backgroundColor: '#1e40af',
    borderLeft: '3px solid #3b82f6',
  },
  planStepCompleted: {
    backgroundColor: '#166534',
    borderLeft: '3px solid #10b981',
  },
  planStepError: {
    backgroundColor: '#7f1d1d',
    borderLeft: '3px solid #ef4444',
  },
  planStepSelected: {
    backgroundColor: '#4338ca',
    borderLeft: '3px solid #6366f1',
  },
  planStepIcon: {
    fontSize: '16px',
    width: '20px',
    textAlign: 'center' as const,
  },
  planStepContent: {
    flex: 1,
  },
  planStepTitle: {
    fontSize: '13px',
    fontWeight: '500',
    color: '#ffffff',
    marginBottom: '2px',
  },
  planStepDescription: {
    fontSize: '11px',
    color: '#d1d5db',
    lineHeight: '1.3',
  },
  inputContainer: {
    padding: '16px',
    borderTop: '1px solid #2a2a2a',
    backgroundColor: '#171717',
  },
  inputWrapper: {
    position: 'relative' as const,
    backgroundColor: '#2a2a2a',
    borderRadius: '12px',
    border: '1px solid #374151',
    transition: 'border-color 0.15s ease',
  },
  inputFocused: {
    borderColor: '#007ACC',
    boxShadow: '0 0 0 1px #007ACC',
  },
  textInput: {
    width: '100%',
    backgroundColor: 'transparent',
    border: 'none',
    borderRadius: '12px',
    padding: '12px 50px 12px 16px',
    color: '#ffffff',
    fontSize: '14px',
    fontFamily: 'inherit',
    outline: 'none',
    resize: 'none' as const,
    minHeight: '44px',
    maxHeight: '120px',
    lineHeight: '1.4',
  },
  sendButton: {
    position: 'absolute' as const,
    right: '8px',
    top: '50%',
    transform: 'translateY(-50%)',
    backgroundColor: '#007ACC',
    color: '#ffffff',
    border: 'none',
    borderRadius: '8px',
    padding: '8px 12px',
    fontSize: '12px',
    fontWeight: '500',
    cursor: 'pointer',
    transition: 'background-color 0.15s ease',
    opacity: 0.9,
  },
  settingsContainer: {
    flex: 1,
    padding: '20px',
    overflowY: 'auto' as const,
  },
  settingsGroup: {
    marginBottom: '24px',
  },
  settingsCard: {
    backgroundColor: '#1f2937',
    border: '1px solid #374151',
    borderRadius: '8px',
    padding: '16px',
    marginBottom: '16px',
  },
  label: {
    display: 'block',
    fontSize: '13px',
    fontWeight: '500',
    color: '#e5e7eb',
    marginBottom: '6px',
  },
  select: {
    width: '100%',
    backgroundColor: '#2a2a2a',
    border: '1px solid #374151',
    borderRadius: '6px',
    padding: '8px 12px',
    color: '#ffffff',
    fontSize: '13px',
    outline: 'none',
    transition: 'border-color 0.15s ease',
  },
  input: {
    width: '100%',
    backgroundColor: '#2a2a2a',
    border: '1px solid #374151',
    borderRadius: '6px',
    padding: '8px 12px',
    color: '#ffffff',
    fontSize: '13px',
    outline: 'none',
    transition: 'border-color 0.15s ease',
  },
  collapsibleHeader: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    padding: '12px 16px',
    backgroundColor: '#1f2937',
    border: '1px solid #374151',
    borderRadius: '8px',
    cursor: 'pointer',
    transition: 'background-color 0.15s ease',
    marginBottom: '8px',
  },
  collapsibleContent: {
    backgroundColor: '#1a1a1a',
    border: '1px solid #374151',
    borderTop: 'none',
    borderRadius: '0 0 8px 8px',
    padding: '16px',
    marginTop: '-8px',
  },
  statusCard: {
    backgroundColor: '#1f2937',
    border: '1px solid #007ACC',
    borderRadius: '8px',
    padding: '16px',
    marginTop: 'auto',
  },
  statusIndicator: {
    width: '8px',
    height: '8px',
    borderRadius: '50%',
    marginRight: '8px',
    display: 'inline-block',
  },
  rightTabContainer: {
    backgroundColor: '#1a1a1a',
    borderBottom: '1px solid #2a2a2a',
    padding: '0 24px',
  },
  rightTabList: {
    display: 'flex',
    gap: '0',
    margin: '0',
    padding: '0',
    listStyle: 'none',
  },
  rightTab: {
    padding: '16px 20px',
    backgroundColor: 'transparent',
    border: 'none',
    color: '#9ca3af',
    fontSize: '14px',
    fontWeight: '500',
    cursor: 'pointer',
    borderBottom: '2px solid transparent',
    transition: 'all 0.15s ease',
  },
  rightTabActive: {
    color: '#007ACC',
    borderBottomColor: '#007ACC',
  },
  rightTabContent: {
    flex: 1,
    padding: '24px',
    backgroundColor: '#212121',
    overflowY: 'auto' as const,
  },
  screenshotPlaceholder: {
    backgroundColor: '#1a1a1a',
    border: '2px dashed #374151',
    borderRadius: '8px',
    height: '400px',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    flexDirection: 'column' as const,
    color: '#6b7280',
    fontSize: '14px',
    gap: '12px',
  },
  executionPlanSection: {
    width: '350px',
    backgroundColor: '#171717',
    borderRight: '1px solid #2a2a2a',
    display: 'flex',
    flexDirection: 'column' as const,
    overflow: 'hidden',
  },
  rightTabSection: {
    flex: 1,
    display: 'flex',
    flexDirection: 'column' as const,
  },
  executionPlanHeader: {
    padding: '16px 20px',
    borderBottom: '1px solid #2a2a2a',
    backgroundColor: '#1a1a1a',
  },
  executionPlanTitle: {
    fontSize: '16px',
    fontWeight: '600',
    color: '#ffffff',
    margin: 0,
    display: 'flex',
    alignItems: 'center',
    gap: '8px',
  },
  executionPlanContent: {
    flex: 1,
    overflowY: 'auto' as const,
    padding: '16px',
  },
  planStepItem: {
    backgroundColor: '#2a2a2a',
    borderRadius: '8px',
    padding: '12px',
    marginBottom: '8px',
    border: '1px solid #374151',
    transition: 'all 0.15s ease',
  },
  planStepHeader: {
    display: 'flex',
    alignItems: 'center',
    gap: '8px',
    marginBottom: '6px',
  },
  planStepStatus: {
    width: '8px',
    height: '8px',
    borderRadius: '50%',
    flexShrink: 0,
  },
  planEmptyState: {
    textAlign: 'center' as const,
    color: '#6b7280',
    padding: '32px 16px',
  },
};

// Add keyframe animation for spinner - safe for SSR
if (typeof document !== 'undefined') {
  const style = document.createElement('style');
  style.textContent = `
    @keyframes spin {
      0% { transform: rotate(0deg); }
      100% { transform: rotate(360deg); }
    }
  `;
  document.head.appendChild(style);
}
